name: cris-hello #my-snap-name # you probably want to 'snapcraft register <name>'
base: core20 # the base snap is the execution environment for this snap
version: '0.4' # just for humans, typically '1.2+git' or '1.3.2'
summary: GNU Hello, the "hello world" snap #Single-line elevator pitch for your amazing snap # 79 char long summary
description: |
  GNU hello prints a friendly greeting.
grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  gnu-hello:
    source: http://ftp.gnu.org/gnu/hello/hello-2.10.tar.gz
    plugin: autotools
